import "./globals.css";
import NavBar from "./component/NavBar";
import { Poppins } from "next/font/google";
import Script from "next/script";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Icon Enterprice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <NavBar />
        {children}

        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-971710724"
          strategy="afterInteractive"
        />

        <Script id="google-ads-base" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            window.gtag = gtag;
            gtag('js', new Date());
            gtag('config', 'AW-971710724');
          `}
        </Script>
      </body>
    </html>
  );
}