import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./component/NavBar";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // Add the weights you need
  variable: '--font-poppins',
});

export const metadata = {
  title: "Icon Enterprice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
